[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; Lokale Bibliotheksordner (falls vorhanden)
lib_extra_dirs =
    ${PROJECT_DIR}/../../shared/lib
    ${PROJECT_DIR}/../shared/lib

; Bibliotheken aus der PlatformIO Registry
lib_deps =
    mobizt/ReadyMail @ ^0.4.2